### ISSUE TITLE
'…' is only available in tvOS 13.0 or newer

### ISSUE THREAD

**Issue by grgar** [nonstrict-hq/CloudStorage#1]
Reproduction steps:

1. Create a new Xcode 12.4 tvOS SwiftUI app template.
2. Set deployment target to tvOS 13.0.  
![Screenshot 2021-03-27 at 10 00 20 am](https://user-images.githubusercontent.com/191085/112717302-9f85d280-8ee3-11eb-9f3d-5edb788e1261.png)
3. Add CloudStorage Swift package.
4. `import CloudStorage` somewhere.
5. Build
6. 💥  
![Screenshot 2021-03-27 at 10 05 55 am](https://user-images.githubusercontent.com/191085/112717365-11f6b280-8ee4-11eb-91ba-57899b7ee6dd.png)

I've tried:

- Adding `.tvOS(.v13)` platform to CloudStorage Package.swift.  
    ```diff
    diff --git a/Package.swift b/Package.swift
    index 29e780d..769993d 100644
    --- a/Package.swift
    +++ b/Package.swift
    @@ -6,6 +6,7 @@ let package = Package(
         platforms: [
             .macOS(.v10_15),
             .iOS(.v13),
    +        .tvOS(.v13),
         ],
         products: [
             .library(name: "CloudStorage", targets: ["CloudStorage"]),
    ```

Any ideas what's up?

**Comment by tomlokhorst** [comment]
I just tried creating an tvOS 13 and tvOS 14 version, both work fine.
Both projects are in the Examples directory in this repository.

**Comment by grgar** [comment]
Thank you for trying this! Ah in your example the package is added to the project directly (not sure how to describe that), whereas I added the package using Swift Package Manager. Using SPM for step 3 causes this issue — dragging the package into the project works. Does that reproduce for you? Is that a SPM bug? SPM is working in prod for iOS and macOS.

**Comment by tomlokhorst** [comment]
Yes, I'm using a local package, because that's easier for me to develop.
But it also works correctly if I switch to a remote package with SPM.

I don't think it's an issue with this library.
Does your project build if you don't include this package?
You can use `@State` instead of `@CloudStorage` to test this.

**Comment by grgar** [comment]
No problem that is a fair workaround for me anyway.

Here's the almost-blank project that doesn't build for me if you've got time to have a look: https://georgegarside.com/o/cloudstoragetv.zip

In this fresh project I'm not using `@CloudStorage` anywhere, just created the template, added this with SPM and imported it in the first file.

**Comment by tomlokhorst** [comment]
Your test project also doesn't build if you remove the reference to CloudStorage.

It uses the SwiftUI `App` protocol, but that is from iOS/tvOS 14. So it won't build as a tvOS 13 project.

Either bump it to tvOS 14, or use a Storyboard app template.

**Comment by grgar** [comment]
Wow that's silly, sorry, I should have checked I put things back, if you switch it to tvOS 14 it still doesn't compile for me with the issues in the original post.

However updating CloudStorage to 0.2.0 in my original proper project and in the one I uploaded has compiled all fine and downgrading to 0.1.0 has issues again. Perhaps editing Xcode's checkout to add `.tvOS(.v13)` and clean doesn't actually clean the build of the SPM package? Anyway, issue resolved, thank you for your help and for this great project.
