### ISSUE TITLE
Doesn't work with `suiteName` UserDefaults

### ISSUE THREAD

**Issue by simanerush** [nonstrict-hq/CloudStorage#4]
I want to be able to use `@CloudStorage` with an extra parameter `store` where I can specify the `UserDefaults` store. For example, I can write
```swift
@AppStorage("myKey", store: UserDefaults(suiteName: "com.myName")) var userPreference = Color.red
```

I really want `@CloudStorage` to have this functionality, too!

**Comment by tomlokhorst** [comment]
This library uses [`NSUbiquitousKeyValueStore `](https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore), which does not support suiteName.

Can you explain what functionality you'd want to have?

**Comment by simanerush** [comment]
Some user preferences are stored in UserDefaults, which are also shared with the app's widget. I'm using `@AppStorage` with `store` parameter to achieve that. I want to be able to save these preferences to iCloud, too. Your implementation works for the main app, but the data is no longer shared with the widget due to `NSUbiquitousKeyValueStore` limitations.. I hope this makes sense!

**Comment by tomlokhorst** [comment]
You can configure your widget to use the NSUbiquitousKeyValueStore from the main app by setting the `com.apple.developer.ubiquity-kvstore-identifier` value in the entitlements of the Widget.

See: [Configuring Common Key-Value Storage for Multiple Apps](https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/iCloudFundametals.html#//apple_ref/doc/uid/TP40012094-CH6-SW26)

If your main app uses the default `$(TeamIdentifierPrefix)$(CFBundleIdentifier)`, in de widget entitlements you can set `$(TeamIdentifierPrefix)com.example.YourMainApp`

**Comment by simanerush** [comment]
This makes sense, thank you!
