### ISSUE TITLE
SwiftUI Threading Issue

### ISSUE THREAD

**Issue by DandyLyons** [nonstrict-hq/CloudStorage#5]
When I run CloudStorage I receive the following error. 

`Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.`

<img width="912" alt="Screenshot 2023-04-13 at 3 47 34 PM" src="https://user-images.githubusercontent.com/72824209/231890175-45b80051-6359-4ff3-b062-3e0e31a83d2d.png">

Perhaps `status = ` should also be inside of the DispatchQueue ?

**Comment by tomlokhorst** [comment]
Indeed, I've made the change and tagged it as the 0.2.1 release.
