### ISSUE TITLE
Missing support for arrays

### ISSUE THREAD

**Issue by mac-cain13** [nonstrict-hq/CloudStorage#8]
The [key-value store also supports arrays](https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore/1417721-set), very convenient to store for example the ordering of certain things. But this doesn't seem to be supported by CloudStorage at the moment, would be great to add support for this.

**Comment by tomlokhorst** [comment]
CloudStorage doesn't support arrays, because AppStorage doesn't support arrays.

The goal of this library is to be compatible with AppStorage, so that one can freely swap between the two.

If AppStorage gains support for arrays, we'll add them here as well.
