### ISSUE TITLE
Store optional enums (Int and String)

### ISSUE THREAD

**Issue by iband** [nonstrict-hq/CloudStorage#9]
Is there a way to store optional enums? For example:

```swift
@CloudStorage(AppStorageKeys.selectedTab) var selectedTab: Tab?

private enum Tab: String {
    case home
    case preferences
}
```

I get error "Type of expression is ambiguous without a type annotation".

**Comment by tomlokhorst** [comment]
Thanks for creating this issue.

This has been fixed in the latest release.
